name: Generate new Tag

on:
 workflow_dispatch:
   inputs:
     tag:
       description: 'Tag For odd-statements module'
       required: true
       type: text
 repository_dispatch:
   types: [generate-new-tag]
 

jobs:
  build-and-tag:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'
      
    - name: Build & Test
      run: make all
      
    - name: Tag the commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ inputs.tag }}
      run: |
        tag_name="v$TAG"
        git tag $tag_name
        git push origin $tag_name

